# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_raster <- function(events, pattern, event_count) {
    .Call(`_rtslib_c_raster`, events, pattern, event_count)
}

c_flushes <- function(data, nevents) {
    .Call(`_rtslib_c_flushes`, data, nevents)
}

c_parameter_ids <- function(event, event_count, start_code, stop_code) {
    .Call(`_rtslib_c_parameter_ids`, event, event_count, start_code, stop_code)
}

c_trialdef <- function(events, pattern, event_count, pattern_count, from_first) {
    .Call(`_rtslib_c_trialdef`, events, pattern, event_count, pattern_count, from_first)
}

